### ISSUE TITLE
CentOS 8 -- xen

### ISSUE THREAD

**Issue by fepitre** [CentOS-virt7/xen#31]
Hi,
Do you have any info about Xen SIG VIRT for CentOS 8?

We are about to implement it in @QubesOS and we would like to help in this direction. Latest xen version 4.12 has all the patches in upstream we required and we don't need to package separately a xen repo only for VM anymore.

Currently, from what I've briefly seen, few dependencies are missing like 'dev86' in EPEL8 which is not a big deal to solve. But, before doing anything, any info would be appreciate to help the concerned people in CentOS/SIG to package XEN in CentOS 8. Thank you.

Regards,
Frédéric

**Comment by fepitre** [comment]
I'm closing this due to no answer in almost one year. Also, I'm building specific Xen and related dependencies on my COPR repositories.

**Comment by karljohns0n** [comment]
See this build: https://cbs.centos.org/koji/buildinfo?buildID=30137

**Comment by fepitre** [comment]
@karljohns0n: thank you for your answer. It seems to not being released yet?
